name: zanis_ios_data_communication
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+10

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  get: ^4.7.2
  get_it: ^8.0.3
  freezed_annotation: ^2.4.4
  injectable: ^2.3.2
  logger: ^2.5.0
  usb_serial: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner:
  injectable_generator:

  freezed:
  json_serializable:

flutter:
  uses-material-design: true
